##
# Origins-Bukkit by SwagPancakes/SwagPannekaker
# Config File (config.yml)
# Version 1
##
Config:
  Origins:
    Blazeborn:
      Max-Health: 20
      Water-Damage:
        Amount: 1
        Delay: 0
        Period-Delay: 10
    Enderian:
      Max-Health: 20
      Water-Damage:
        Amount: 1
        Delay: 0
        Period-Delay: 10
      Ability:
        Cooldown: 2
    Merling:
      Max-Health: 20
      Air-Breathing:
        Max-Time: 120
        Damage:
          Amount: 1
          Delay: 0
          Period-Delay: 10
      Bossbar:
        Air-Breathing-Timer:
          BarColor:
            On-Decrease: BLUE
            On-Increase: GREEN
            On-Drowning: RED
          BarStyle:
            On-Decrease: SOLID
            On-Increase: SOLID
            On-Drowning: SOLID
